### ISSUE TITLE
move stextools to github/slatex

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#1]
that would make them much more visible. It might also be good to give me more access, so that I can do more with the issues.

**Comment by jfschaefer** [comment]
Done

**Comment by kohlhase** [comment]
excellent, thanks. 
Does the transfer of issues work now?

**Comment by jfschaefer** [comment]
Yes, I've just successfully transferred the two issues from `sTeX-React`

**Comment by kohlhase** [comment]
great.
