### ISSUE TITLE
colors in choices are gone. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#16]
with the update, I was asked to install pygments, but now the colors in the choices are gone. 
<img width="1132" alt="Screenshot 2024-10-18 at 15 48 05" src="https://github.com/user-attachments/assets/e968a056-67fc-428a-a0dc-fd20169b795e">

**Comment by jfschaefer** [comment]
Odd - for me it looks like this:
![image](https://github.com/user-attachments/assets/2fe8274d-f3f7-4d97-89e0-9009c30ab454)

Maybe your terminal does not support true color - can you try
```bash
python3 -m stextools --use-true-color false srify annotated.retake.tex
```

**Comment by kohlhase** [comment]
I am not surprised, I do not know what is happening.

**Comment by jfschaefer** [comment]
This should be fixed now.
The reason is that not all terminal emulators support true color.
This can now be specified with the `--use-true-color` option.
