### ISSUE TITLE
new interaction modifier !

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#17]
For most of the actions in `srify` I would like to have the post-modifier `!`, which means "and do that for the rest of the file". So `s!` means skip this for the rest of the file (this only one). `S!` does not make sense. But `7!` does multiple annotations with the same symbol (probably only for the exactly same word). 

The `!!` modifer could extend this to all files still to be considered. But I guess that may be a lot more work. 

I believe this will be immensely useful.

**Comment by jfschaefer** [comment]
We have some modifiers like this by now.
I guess we might need more specific issues if it can be improved in some way.
