### ISSUE TITLE
stextools: structures, and srify: adding \usestructure

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#19]
Some symbols come from math structures or their extensions. So, when a `\symdef` is inside a `{mathstructure}{foo}`,  `{extstructure}{bar}{foo}`, or an `{extstructure*}{bar}{foo}`, inside a `{module}{FOO}` then the `\usemodule{FOO}` must  be accompanied by a `\usestructure{foo}` to make the symbol visible. 

Also, a `\begin{mathstructure}{foo}[foobar]` will add a verbalization `foobar` to the symbol `FOO?foo`. And similarly for `\begin{extstructure}{bar}{foo}[foobar]` (also in the `*`variant).

**Comment by jfschaefer** [comment]
This has been implemented for quite some time now
