### ISSUE TITLE
(maybe) add a session concept to srify

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#25]
I often find myself in the situation that I started with `srify *.tex` for a larger list of sTeX files, and I have to quit the session in the middle (because something comes up). Often I want to pick this up again later, and either continue, or sometimes even re-run the process with the "local skip decisions' that I did not "document" in the files, because i want to revisit them. 

Maybe we could save this in form of a "session" that I can take up or revisit later? 

I have the feeling that this would be an important feature, but cannot quite pin down what it would be yet.

**Comment by jfschaefer** [comment]
This works now.
At the moment, there are no "local skip decisions" (`s` only forwards the cursor), but once they are implemented, they would also persist.
