### ISSUE TITLE
new interaction: e to escape to editor 

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#27]
Sometimes I do not like what I see in the file I am annotating. It would be very good if I could just type `e` and get an editor (via the config file which might allow configurations for multiple editors available, or as a fallback the `$EDITOR` variable ) with the the current file preloaded. After exiting the editor, the  annotation session is resumed with the new file. 

This is a simpler version of #24.

**Comment by jfschaefer** [comment]
Done
