### ISSUE TITLE
language-specific stemmer

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#30]
sTeX has the convention that the primary language is given in the file extension, e.g. foo.en.tex for Englisch. `srify` should use that languge for the file.

**Comment by jfschaefer** [comment]
This works now.
However, currently only German and English stemmers are supported.
The following languages are supported by nltk and can therefore easily be added:
`arabic danish dutch english finnish french german hungarian italian norwegian porter portuguese romanian russian spanish swedish`
