### ISSUE TITLE
--inputref to follow the \inputref directives

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#31]
Often I want to annotate a whole document (i.e. all the included sTeX files). So I would like to give `srify` an option `--inputref` or `-i` to instruct it to follow them: for each `\inputref{foo.en}` to interrupt the current annotation and go to the  file `foo.en.tex` first.

**Comment by jfschaefer** [comment]
This was implemented in 47b0dd2cb15dc025e49fc6642378000a7a49c820
However, instead of a command line option, `srify` will ask you in the beginning if `\inputref`s should be followed (if there are any).
