### ISSUE TITLE
wrong placement of \usemodule in frame

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#34]
I just came across this: 
<img width="670" alt="Screenshot 2024-10-30 at 05 50 18" src="https://github.com/user-attachments/assets/1d53f252-a829-46bb-a429-bf052155e807">
It seems that `srify` has placed the `\usemodule` directive directly after the `\begin{frame}` (as intended) but has neglected that there is an optional argument.

**Comment by jfschaefer** [comment]
This should be fixed by now (bba56ca98f3bb650be25cb62932aeae7f80f3aaf)
