### ISSUE TITLE
new srify option -t

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#36]
Currently, `srify` tries hard to put the `\usemodule` directives into the right place (e.g. inside a `frame` env when no `smodule` can be found. This is great for files that are intended for inclusion, but leads to duplication in files that are never intended to be taken apart into reusable fragments. Therefore it would be great to have a command-line option e.g. `-t` to `srify` that tells `srify` to put all `\usemodule` at the top of the file, i.e. directly after the `\begin{document}`. 

It might be useful to have an interaction `t` (or so) that allows to switch into this mode, if we have forgotten the option when calling. 

I am not sure what to do with the "placment strategy" when passing into a `\inputref` via #32 though.

**Comment by jfschaefer** [comment]
I think this is solved with the `[t]` command.

**Comment by kohlhase** [comment]
yes
