### ISSUE TITLE
with \inputrefs enabled, srify proceeds from the back

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#42]
I am trying `srify` on `MathHub/courses/FAU/LBS/course/source/course/sec/notes.tex` with `\inputref` enabled. Then it first focuses on `../sec/concl.tex` and then proceeds from the back. That is not nice, since we want the front to be ready for the students first.

**Comment by jfschaefer** [comment]
That makes sense. At the moment, input dependencies are unordered, but that should be easy to change.
