### ISSUE TITLE
new "annotate as" interaction

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#43]
Sometimes I get an annotation for the word `foo`, but I know that this is really a synonym for the concept `barsymbol` that has the verbalization `bar`, so I want to annotate it as if it were the word `bar`, and want to get `\sr{barsymbol}{foo}`. This is independent from whether `barsymbol` actually has a verbalization `foo`.

**Comment by jfschaefer** [comment]
I've implemented something for this (command `[l]` for `lookup`). It requires `fzf` for the search (installation info is printed when the command is used).
