### ISSUE TITLE
interaction for separating a compond

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#53]
Sometimes `srify` directly focuses on a compound, e.g. on `variable name` in `MathHub/courses/Jacobs/ComSem/source/nlfrags/snip/comprehension.en.tex` and while we have `n` and `p` to make compounds we do not have any interaction to break one. We could use `b` for that.

**Comment by jfschaefer** [comment]
I've implemented it as `[N]` and `[P]` as the opposites of `[n]` and `[p]`.
This is relatively intuitive for me, personally. Not sure if something else would be better...
