### ISSUE TITLE
interactions  "include next/previous word"

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#6]
Imagine that the srify highlights/selects the word `bar` in the text `foo bar baz` then I would like to have two new interactions: 
- `p` for "include previous word" which would extend the selection to `foo bar` and looks for symbols for that. 
- `n` for "include next word" finding symbols for `bar baz`.

**Comment by jfschaefer** [comment]
Implemented in 1af2c6af9f23f3b3e914a35a367eb9d67d446664
