### ISSUE TITLE
Trouble with `gitlab` dependency

### ISSUE THREAD

**Issue by lambdaTotoro** [slatex/stextools#67]
The newest version introduces `gitlab` as a dependency, but when I try to install it, I get an error message:

```
totoro@goedel:~/Development/FAU/vc/github.com/sLaTeX/stextools % python3 -m pip install gitlab
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following yanked versions: 1.0.0, 1.0.1, 1.0.2
ERROR: Could not find a version that satisfies the requirement gitlab (from versions: none)
ERROR: No matching distribution found for gitlab
```

It seems [the entire project was yanked](https://pypi.org/project/gitlab/) (i.e. [severely deprecated](https://adamj.eu/tech/2021/09/20/how-to-fix-pip-yanked-version-warnings/#:~:text=PyPI%20allows,installs%20to%20succeed)) because there's another, more complete wrapper library available. If we seriously do need this library, the dependency should pin a version (probably `gitlab == 1.0.2`, that let's the install go ahead with a printed warning). Otherwise, the dependency should be adapted to `python-gitlab` or something else.

**Comment by jfschaefer** [comment]
Oh no, the dependency should actually be `python-gitlab`. Thanks for pointing that out!
I'll fix it right away.
