### ISSUE TITLE
help is garbled on MacOS and zsh

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#71]
I get 
<img width="1063" alt="Screenshot 2024-12-08 at 07 20 00" src="https://github.com/user-attachments/assets/2154294d-cd44-4c59-91ea-90991e0bc570">

**Comment by jfschaefer** [comment]
I've fixed this (on `devel`).
Apparently, your pager doesn't support the ANSI escape codes.
Maybe I should prioritize `less` over the `PAGER` environment variable...
