### ISSUE TITLE
focus (f) exists immediately

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#72]
When I hit `f`, snify thinks a bit and then directly exits. `f!` works nicely however. 

<img width="1049" alt="Screenshot 2024-12-08 at 07 24 03" src="https://github.com/user-attachments/assets/9b92025d-ceee-440b-8c26-8e4c45336577">

**Comment by jfschaefer** [comment]
I can't fully reproduce this, but I found a closely related bug that I've fixed now (on `devel`).
I'll close the issue for now in the hope that it'll fix your bug as well - otherwise, please re-open :)
