### ISSUE TITLE
importmodule duplication

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#8]
It looks as if importmodule duplication can happen. I assume the added importmodules only check the cache and not the already-added local imports. 
<img width="590" alt="Screenshot 2024-10-14 at 20 59 28" src="https://github.com/user-attachments/assets/b98a4b03-4cd0-41a2-9f48-a4545b38d831">
It seems that there are also `\importmodule` or `\usemodule` declarations missing, 

See `MathHub/courses/FAU/AI/hwexam/source/SS24/exams/annotated.exam.tex` for a file that was annotated from scratch with `srify` as an example.

**Comment by jfschaefer** [comment]
I've re-written this part completely, and I think it's fixed now.
If not, please re-open.
